// Mock data for initial dashboard -- will be replaced with Airtable data

export const MOCK_TASKS = [
  // INBOX
  {
    id: 't1',
    name: 'Mother\'s Day Campaign \u2014 Full Creative Suite',
    description: 'Generate complete campaign creative for Mother\'s Day 2026. Need ad copy, social posts, video scripts, landing page, and email sequence.',
    agent: null,
    status: 'Inbox',
    contentType: 'Ad Copy',
    platform: ['Facebook', 'Instagram', 'TikTok'],
    campaign: "Mother's Day 2026",
    priority: 'High',
    tags: ['gratitude', 'celebration', 'paid'],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't2',
    name: 'Direct-to-Fan Landing Page \u2014 Artist Discovery',
    description: 'Create a landing page for the new direct-to-fan lane. Position Songfinch as a platform where fans can commission songs directly from artists they love.',
    agent: null,
    status: 'Inbox',
    contentType: 'Landing Page',
    platform: ['Website'],
    campaign: 'D2F Launch',
    priority: 'High',
    tags: ['identity'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't3',
    name: 'Retargeting Ad Sequence \u2014 Cart Abandoners',
    description: 'Build a 3-touch retargeting sequence for users who started a song order but didn\'t complete. Focus on the emotional payoff they\'re leaving behind.',
    agent: null,
    status: 'Inbox',
    contentType: 'Ad Copy',
    platform: ['Facebook', 'Instagram'],
    campaign: 'Retargeting',
    priority: 'Medium',
    tags: ['retargeting', 'paid'],
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't4',
    name: 'Competitor Research \u2014 Cameo, Memento, AI Music Apps',
    description: 'Deep dive on competitor positioning. How are they messaging? What emotional territory are they claiming? Where are the gaps?',
    agent: null,
    status: 'Inbox',
    contentType: 'Blog Post',
    platform: [],
    campaign: 'Research',
    priority: 'Medium',
    tags: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  // ASSIGNED
  {
    id: 't5',
    name: 'Father\'s Day Early Bird \u2014 Ad Copy Batch',
    description: 'Create 5 ad copy variations for Father\'s Day early bird campaign. Focus on the "tribute" and "gratitude" emotional pillars.',
    agent: 'HOOK',
    status: 'Assigned',
    contentType: 'Ad Copy',
    platform: ['Facebook', 'Instagram'],
    campaign: "Father's Day 2026",
    priority: 'High',
    tags: ['tribute', 'gratitude', 'paid'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't6',
    name: 'Weekly Social Content \u2014 10 Posts',
    description: 'Create 10 organic social posts for this week. Mix of platforms. Focus on real customer moments and artist stories.',
    agent: 'PULSE',
    status: 'Assigned',
    contentType: 'Social Post',
    platform: ['Instagram', 'TikTok', 'Twitter/X'],
    campaign: 'Organic Weekly',
    priority: 'Medium',
    tags: ['organic'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't7',
    name: 'Artist Spotlight \u2014 Featured Artist of the Month',
    description: 'Write an in-depth artist spotlight for the blog. Tell their story, why they joined Songfinch, a memorable song they created.',
    agent: 'STORY',
    status: 'Assigned',
    contentType: 'Artist Spotlight',
    platform: ['Blog'],
    campaign: 'Artist Spotlights',
    priority: 'Medium',
    tags: ['identity'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  // IN PROGRESS
  {
    id: 't8',
    name: 'Video Ad Script \u2014 "The Moment They Hear It"',
    description: '30-second video ad script showing real reactions of people hearing their custom songs for the first time. UGC style.',
    agent: 'LENS',
    status: 'In Progress',
    contentType: 'Video Script',
    platform: ['TikTok', 'Instagram', 'Facebook'],
    campaign: 'Brand Awareness',
    priority: 'High',
    tags: ['celebration', 'memory', 'paid'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't9',
    name: 'SEO Blog \u2014 "Best Personalized Gifts 2026"',
    description: 'Write a comprehensive SEO article targeting "best personalized gifts 2026". Position Songfinch as the emotional gold standard.',
    agent: 'FLOW',
    status: 'In Progress',
    contentType: 'SEO Content',
    platform: ['Blog', 'Website'],
    campaign: 'SEO',
    priority: 'Medium',
    tags: ['celebration', 'organic'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  {
    id: 't10',
    name: 'Graduation Season \u2014 Social Content Plan',
    description: 'Build a 2-week social content calendar for graduation season. Parents and friends commissioning songs for graduates.',
    agent: 'PULSE',
    status: 'In Progress',
    contentType: 'Social Post',
    platform: ['Instagram', 'TikTok', 'Facebook'],
    campaign: 'Graduation 2026',
    priority: 'High',
    tags: ['celebration', 'tribute', 'organic'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    driveLink: '',
    canvaLink: '',
  },
  // REVIEW
  {
    id: 't11',
    name: 'Wedding Season Landing Page',
    description: 'Landing page for wedding song commissions. Headline: "Your love story deserves its own soundtrack."',
    agent: 'FLOW',
    status: 'Review',
    contentType: 'Landing Page',
    platform: ['Website'],
    campaign: 'Wedding Season',
    priority: 'High',
    tags: ['celebration', 'memory'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    output: 'H1: Your love story deserves its own soundtrack.\nSubhead: A real artist. Your real story. One unforgettable song.\n\n[Full landing page copy ready for review]',
    driveLink: '',
    canvaLink: 'https://www.canva.com/design/example-wedding',
  },
  {
    id: 't12',
    name: 'Instagram Carousel \u2014 "5 Moments Worth a Song"',
    description: '5-slide carousel showing different life moments that deserve a custom song. Each slide is an emotional pillar.',
    agent: 'PULSE',
    status: 'Review',
    contentType: 'Social Post',
    platform: ['Instagram'],
    campaign: 'Brand Awareness',
    priority: 'Medium',
    tags: ['celebration', 'gratitude', 'memory', 'identity', 'tribute'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    driveLink: '',
    canvaLink: 'https://www.canva.com/design/example-carousel',
  },
  // DONE
  {
    id: 't13',
    name: 'Valentine\'s Day Retargeting Sequence',
    description: '3-touch retargeting ads for Valentine\'s Day campaign. Focused on couples and romantic partners.',
    agent: 'HOOK',
    status: 'Done',
    contentType: 'Ad Copy',
    platform: ['Facebook', 'Instagram'],
    campaign: "Valentine's Day 2026",
    priority: 'High',
    tags: ['celebration', 'memory', 'retargeting'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    driveLink: 'https://drive.google.com/drive/folders/1x9BK_usoOu2aAXBtQSxUgD_2-o3Oqiyk',
    canvaLink: 'https://www.canva.com/design/example-vday',
  },
  {
    id: 't14',
    name: 'Blog Post \u2014 "Why Music Is the Most Personal Gift"',
    description: 'Thought leadership blog post about why music activates memory and emotion more than any other medium.',
    agent: 'STORY',
    status: 'Done',
    contentType: 'Blog Post',
    platform: ['Blog'],
    campaign: 'Content Marketing',
    priority: 'Medium',
    tags: ['memory', 'identity'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    driveLink: 'https://drive.google.com/drive/folders/1x9BK_usoOu2aAXBtQSxUgD_2-o3Oqiyk',
    canvaLink: '',
  },
]

export const MOCK_ACTIVITY = [
  {
    id: 'a1',
    agent: 'HOOK',
    action: 'completed',
    task: "Valentine's Day Retargeting Sequence",
    details: 'Generated 3-touch retargeting sequence with 6 A/B variants. Ready for Meta upload.',
    type: 'Content Generated',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'a2',
    agent: 'LENS',
    action: 'started',
    task: 'Video Ad Script \u2014 "The Moment They Hear It"',
    details: 'Beginning UGC-style video script. Targeting 30s format for TikTok and Reels.',
    type: 'Task Created',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'a3',
    agent: 'MUSE',
    action: 'assigned',
    task: "Father's Day Early Bird \u2014 Ad Copy Batch",
    details: 'Routing to HOOK. Brief: Focus on tribute + gratitude pillars. 5 variations needed.',
    type: 'Task Created',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'a4',
    agent: 'FLOW',
    action: 'submitted for review',
    task: 'Wedding Season Landing Page',
    details: 'Landing page complete. H1: "Your love story deserves its own soundtrack." Needs creative director review.',
    type: 'Review Needed',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'a5',
    agent: 'PULSE',
    action: 'submitted for review',
    task: 'Instagram Carousel \u2014 "5 Moments Worth a Song"',
    details: '5-slide carousel ready. Each slide maps to an emotional pillar. Needs copy review.',
    type: 'Review Needed',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'a6',
    agent: 'SCOUT',
    action: 'completed research',
    task: 'Weekly Competitor Monitoring',
    details: 'Cameo launched "Cameo Songs" feature. Memento raised Series A. Full report in Drive.',
    type: 'Content Generated',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'a7',
    agent: 'STORY',
    action: 'completed',
    task: 'Blog Post \u2014 "Why Music Is the Most Personal Gift"',
    details: '1,800 word article. Targeting "personalized music gift" keyword cluster. Published to blog.',
    type: 'Approved',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'a8',
    agent: 'MUSE',
    action: 'created campaign',
    task: "Mother's Day Campaign \u2014 Full Creative Suite",
    details: 'New campaign brief incoming. Need full creative suite: ads, social, video, landing page, email.',
    type: 'Task Created',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
]

export function getTasksByStatus(status) {
  return MOCK_TASKS.filter(t => t.status === status)
}

export function getTasksByAgent(agentName) {
  return MOCK_TASKS.filter(t => t.agent === agentName)
}
