// Slack Incoming Webhook Notifier — Pushes pipeline events to Slack
// Uses Block Kit for rich message formatting
// Non-blocking: all calls are fire-and-forget, never stalls the pipeline

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL

const AGENT_EMOJI = {
  CMO: '👔', CHIEF: '🎖️', MUSE: '🎨', HOOK: '🪝', PULSE: '📱',
  LENS: '🎬', STORY: '📖', SCOUT: '🔭', FLOW: '🌊', PIXEL: '🖼️',
  System: '⚙️',
}

const STATUS_COLOR = {
  approved: '#4ade80',    // green
  revised: '#f59e0b',     // amber
  planned: '#818cf8',     // indigo
  completed: '#22d3ee',   // cyan
  error: '#ef4444',       // red
  info: '#64748b',        // slate
  image: '#c084fc',       // purple
}

// ── MAIN SENDER ─────────────────────────────────

async function sendSlack(blocks, text = 'Mission Control Update') {
  if (!SLACK_WEBHOOK_URL) return // Silently skip if not configured

  try {
    await fetch(SLACK_WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, blocks }),
    })
  } catch {
    // Non-blocking — pipeline never stalls for Slack
  }
}

// ── EVENT-SPECIFIC NOTIFIERS ─────────────────────

// Content approved by CHIEF
export async function notifyApproved({ task, agent, score, summary, imageGenerated }) {
  const emoji = AGENT_EMOJI[agent] || '🤖'
  const scoreBar = score >= 4.0 ? '🟢' : score >= 3.0 ? '🟡' : '🔴'

  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `✅ *Content Approved*\n*${task}*\n${emoji} ${agent} → ${scoreBar} ${score}/5`,
      },
    },
    summary && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: summary.substring(0, 200) }],
    },
    imageGenerated && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: '🖼️ Visual companion auto-generated by PIXEL' }],
    },
  ].filter(Boolean)

  await sendSlack(blocks, `✅ Approved: ${task} (${score}/5)`)
}

// Content sent back for revision
export async function notifyRevised({ task, agent, score, feedback }) {
  const emoji = AGENT_EMOJI[agent] || '🤖'

  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `🔄 *Revision Requested*\n*${task}*\n${emoji} ${agent} → Score: ${score}/5`,
      },
    },
    feedback && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `💬 ${feedback.substring(0, 250)}` }],
    },
  ].filter(Boolean)

  await sendSlack(blocks, `🔄 Revision: ${task} (${score}/5)`)
}

// Review cycle summary
export async function notifyReviewCycle({ reviewed, approved, revised, errors }) {
  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `🎖️ *CHIEF Review Cycle Complete*\n📊 Reviewed: *${reviewed}* | ✅ Approved: *${approved}* | 🔄 Revised: *${revised}*${errors > 0 ? ` | ❌ Errors: *${errors}*` : ''}`,
      },
    },
  ]

  await sendSlack(blocks, `Review cycle: ${approved} approved, ${revised} revised`)
}

// Campaign planned by CMO
export async function notifyCampaignPlanned({ campaign, tasksCreated, contentTypes, territories }) {
  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `👔 *CMO Campaign Planned*\n📋 *${campaign || 'New Campaign'}*\n📝 ${tasksCreated} tasks created`,
      },
    },
    contentTypes && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `Types: ${contentTypes.join(', ')}` }],
    },
    territories && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `Territories: ${territories.join(', ')}` }],
    },
  ].filter(Boolean)

  await sendSlack(blocks, `Campaign planned: ${tasksCreated} tasks`)
}

// Cron pipeline cycle complete
export async function notifyCronCycle({ processed, assigned, planned, reviewed, errors, duration }) {
  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: [
          '⚙️ *Pipeline Cycle Complete*',
          `📝 Processed: *${processed}* | 📋 Assigned: *${assigned}*`,
          planned > 0 ? `📊 Planned: *${planned}* new tasks` : null,
          reviewed > 0 ? `🎖️ Reviewed: *${reviewed}*` : null,
          errors > 0 ? `❌ Errors: *${errors}*` : null,
          `⏱️ ${duration}`,
        ].filter(Boolean).join('\n'),
      },
    },
  ]

  await sendSlack(blocks, `Pipeline: ${processed} processed, ${assigned} assigned`)
}

// Image generated
export async function notifyImageGenerated({ task, preset, url }) {
  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `🖼️ *Image Generated*\n*${task}*\nPreset: ${preset || 'default'}`,
      },
    },
    url && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `<${url}|View Image>` }],
    },
  ].filter(Boolean)

  await sendSlack(blocks, `🖼️ Image: ${task}`)
}

// Pipeline health alert
export async function notifyPipelineAlert({ type, message, details }) {
  const icon = type === 'stall' ? '🚨' : type === 'low_queue' ? '⚠️' : 'ℹ️'

  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `${icon} *Pipeline Alert: ${type.toUpperCase()}*\n${message}`,
      },
    },
    details && {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: details.substring(0, 300) }],
    },
  ].filter(Boolean)

  await sendSlack(blocks, `${icon} Alert: ${message}`)
}

// Daily digest summary
export async function notifyDailyDigest({ totalTasks, completed, inProgress, quality, topAgent, velocity }) {
  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: [
          '📊 *Daily Roundtable Digest*',
          `━━━━━━━━━━━━━━━━━━━━━`,
          `📋 Total Tasks: *${totalTasks}* | ✅ Completed: *${completed}*`,
          `🔄 In Progress: *${inProgress}*`,
          quality ? `⭐ Avg Quality: *${quality}/5*` : null,
          velocity ? `🚀 Velocity: *${velocity}/day*` : null,
          topAgent ? `🏆 Top Agent: *${topAgent}*` : null,
        ].filter(Boolean).join('\n'),
      },
    },
  ]

  await sendSlack(blocks, `Daily digest: ${completed} completed, quality ${quality}/5`)
}
